Add loki logs to ruff pipeline

diff --git a/.github/workflows/ruff_format.yml b/.github/workflows/ruff_format.yml
--- a/.github/workflows/ruff_format.yml
+++ b/.github/workflows/ruff_format.yml
@@ -4,6 +4,8 @@ on:
   push:
     branches:
       - "**"
+    tags:
+      - "*"
   pull_request:
     branches:
       - "**"
@@ -13,6 +15,10 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
+      - name: Start time
+        id: start_time
+        run: echo "start_time=$(date +%s)" >> $GITHUB_OUTPUT
+
       - name: Checkout code
         uses: actions/checkout@v4
 
@@ -20,10 +26,35 @@ jobs:
         run: pip install ruff
 
       - name: Check code format
+        id: ruff
         run: |
-          ruff check .
+          ruff_output=$(ruff check . || true)
+          echo "$ruff_output"
 
-          if [[ $(ruff check .) != "All checks passed!" ]]; then
-            echo "One or more files are not formatted correctly."
-            exit 1
+          errors=$(echo "$ruff_output" | grep "Found .* errors" | grep -oP "\d+")
+
+          if [[ -n $errors && $errors -gt 0 ]]; then
+            echo "errors=$errors" >> $GITHUB_OUTPUT
+          else
+            echo "errors=0" >> $GITHUB_OUTPUT
           fi
+
+      - name: Send results to Loki
+        if: always()
+        env:
+          LOKI_ADDRESS: "https://loki.shintolabs.net"
+          LOKI_USERNAME: ${{ secrets.LOKI_USERNAME }}
+          LOKI_PASSWORD: ${{ secrets.LOKI_PASSWORD }}
+          REPOSITORY: ${{ github.repository }}
+          WORKFLOW: ${{ github.workflow }}
+          JOB: ${{ github.job }}
+          STATUS: ${{ job.status }}
+          RUN_ID: ${{ github.run_id }}
+          RUN_NUMBER: ${{ github.run_number }}
+          ACTOR: ${{ github.actor }}
+          URL: ${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }}
+          REF: ${{ github.ref }}
+          START_TIME: ${{ steps.start_time.outputs.start_time }}
+          VALUES: 'ruff_errors="${{ steps.ruff.outputs.errors }}"'
+        run: |
+          ./scripts/send_to_loki.sh
